"""initial_schema

Revision ID: 8220336cb266
Revises: 
Create Date: 2026-04-14 16:30:23.023534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8220336cb266'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('site_type', sa.Enum('static', 'php', 'node', 'python', 'proxy', 'wordpress', name='sitetype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'stopped', 'error', name='sitestatus'), nullable=False),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('env_vars', sa.Text(), nullable=True),
    sa.Column('upstream_url', sa.String(length=512), nullable=True),
    sa.Column('git_repo', sa.String(length=512), nullable=True),
    sa.Column('git_branch', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_domain'), 'sites', ['domain'], unique=True)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('cert_path', sa.String(length=512), nullable=False),
    sa.Column('key_path', sa.String(length=512), nullable=False),
    sa.Column('ca_signed', sa.Boolean(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_table('deploy_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('rq_job_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='jobstatus'), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deploy_jobs_id'), 'deploy_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_deploy_jobs_rq_job_id'), 'deploy_jobs', ['rq_job_id'], unique=False)
    op.create_table('sftp_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('home_dir', sa.String(length=512), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_sftp_accounts_id'), 'sftp_accounts', ['id'], unique=False)
    op.create_table('site_databases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=64), nullable=False),
    sa.Column('db_user', sa.String(length=64), nullable=False),
    sa.Column('db_password_hash', sa.String(length=128), nullable=False),
    sa.Column('engine', sa.Enum('postgres', 'mysql', name='databaseengine'), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_name', 'engine', name='uq_site_databases_name_engine')
    )
    op.create_index(op.f('ix_site_databases_id'), 'site_databases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_databases_id'), table_name='site_databases')
    op.drop_table('site_databases')
    op.drop_index(op.f('ix_sftp_accounts_id'), table_name='sftp_accounts')
    op.drop_table('sftp_accounts')
    op.drop_index(op.f('ix_deploy_jobs_rq_job_id'), table_name='deploy_jobs')
    op.drop_index(op.f('ix_deploy_jobs_id'), table_name='deploy_jobs')
    op.drop_table('deploy_jobs')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_domain'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
