"""Nginx reverse proxy configuration generator."""
import json
import logging
import re
from pathlib import Path

from app.config import settings
from app.models import Site

log = logging.getLogger(__name__)

PROXY_CONF_DIR = Path(settings.proxy_config_dir)
_CLIENT_MAX_BODY_SIZE_ENV_KEY = "LINKHOSTING_CLIENT_MAX_BODY_SIZE"
_CLIENT_MAX_BODY_SIZE_RE = re.compile(r"^(0|[1-9]\d*)([kKmMgG])?$")

VHOST_TEMPLATE_HTTP = """\
# Auto-generated by LinkHosting — do not edit manually
server {{
    listen 80;
    server_name {domain};
{client_max_body_size_line}

    location / {{
        proxy_pass http://{upstream}:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""

VHOST_TEMPLATE_HTTPS = """\
# Auto-generated by LinkHosting — do not edit manually
server {{
    listen 80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl;
    server_name {domain};
{client_max_body_size_line}

    ssl_certificate     /etc/nginx/certs/{site_name}/cert.pem;
    ssl_certificate_key /etc/nginx/certs/{site_name}/key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {{
        proxy_pass http://{upstream}:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""


def _container_port(site: Site) -> int:
    from app.models import SiteType
    ports = {
        SiteType.static: 80,
        SiteType.php: 80,
        SiteType.node: 3000,
        SiteType.python: 8000,
        SiteType.proxy: 80,
        SiteType.wordpress: 80,
    }
    return ports.get(site.site_type, 80)


def _upstream_name(site: Site) -> str:
    """Return the upstream hostname for nginx proxy_pass.

    For WordPress sites this is the fully-qualified Docker container name
    (``<project>-<service>-1``) which Docker's embedded DNS resolves reliably
    within the ``linkhosting_proxy`` network.  For all other site types the
    conventional ``site-<name>`` hostname is used.
    """
    from app.models import SiteType
    if site.site_type == SiteType.wordpress:
        from app.services.wordpress import get_wordpress_container_name
        return get_wordpress_container_name(site.name)
    return f"site-{site.name}"


def _client_max_body_size_line(site: Site) -> str:
    if not site.env_vars:
        return ""
    try:
        env_vars = json.loads(site.env_vars)
    except (json.JSONDecodeError, TypeError):
        return ""
    if not isinstance(env_vars, dict):
        return ""

    value = str(env_vars.get(_CLIENT_MAX_BODY_SIZE_ENV_KEY, "")).strip()
    if not value or not _CLIENT_MAX_BODY_SIZE_RE.match(value):
        return ""
    return f"    client_max_body_size {value};"


def write_vhost(site: Site, tls: bool = False) -> Path:
    """Write an Nginx vhost config for the site."""
    PROXY_CONF_DIR.mkdir(parents=True, exist_ok=True)
    conf_path = PROXY_CONF_DIR / f"{site.name}.conf"

    port = _container_port(site)
    upstream = _upstream_name(site)
    template = VHOST_TEMPLATE_HTTPS if tls else VHOST_TEMPLATE_HTTP
    content = template.format(
        site_name=site.name,
        upstream=upstream,
        domain=site.domain,
        port=port,
        client_max_body_size_line=_client_max_body_size_line(site),
    )

    if settings.dev_mode:
        log.info("[DEV] Would write vhost config to %s:\n%s", conf_path, content)
    else:
        conf_path.write_text(content)
        log.info("Wrote vhost config for %s -> %s", site.domain, conf_path)

    return conf_path


def remove_vhost(site_name: str) -> None:
    """Remove vhost config for a site."""
    conf_path = PROXY_CONF_DIR / f"{site_name}.conf"
    if settings.dev_mode:
        log.info("[DEV] Would remove vhost config %s", conf_path)
        return
    if conf_path.exists():
        conf_path.unlink()
        log.info("Removed vhost config %s", conf_path)


def reload_proxy() -> None:
    """Signal Nginx to reload its configuration via the Docker Engine API."""
    if settings.dev_mode:
        log.info("[DEV] Would reload nginx")
        return

    from app.services.docker_api import exec_in_container

    exit_code, output = exec_in_container("lh-proxy", ["nginx", "-s", "reload"])
    if exit_code != 0:
        log.warning("nginx reload failed (exit %d): %s", exit_code, output)
    else:
        log.info("Nginx reloaded")
