"""Nginx reverse proxy configuration generator."""
import logging
from pathlib import Path

from app.config import settings
from app.models import Site

log = logging.getLogger(__name__)

PROXY_CONF_DIR = Path(settings.proxy_config_dir)

VHOST_TEMPLATE_HTTP = """\
# Auto-generated by LinkHosting — do not edit manually
server {{
    listen 80;
    server_name {domain};

    location / {{
        proxy_pass http://site-{name}:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""

VHOST_TEMPLATE_HTTPS = """\
# Auto-generated by LinkHosting — do not edit manually
server {{
    listen 80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl;
    server_name {domain};

    ssl_certificate     /etc/nginx/certs/{name}/cert.pem;
    ssl_certificate_key /etc/nginx/certs/{name}/key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {{
        proxy_pass http://site-{name}:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""


def _container_port(site: Site) -> int:
    from app.models import SiteType
    ports = {
        SiteType.static: 80,
        SiteType.php: 80,
        SiteType.node: 3000,
        SiteType.python: 8000,
        SiteType.proxy: 80,
        SiteType.wordpress: 80,
    }
    return ports.get(site.site_type, 80)


def _upstream_name(site: Site) -> str:
    """Return the upstream hostname for nginx proxy_pass."""
    from app.models import SiteType
    if site.site_type == SiteType.wordpress:
        # WordPress service is named via _wordpress_service_name in the per-site compose project
        from app.services.wordpress import _wordpress_service_name
        return _wordpress_service_name(site.name)
    return f"site-{site.name}"


def write_vhost(site: Site, tls: bool = False) -> Path:
    """Write an Nginx vhost config for the site."""
    PROXY_CONF_DIR.mkdir(parents=True, exist_ok=True)
    conf_path = PROXY_CONF_DIR / f"{site.name}.conf"

    port = _container_port(site)
    upstream = _upstream_name(site)
    template = VHOST_TEMPLATE_HTTPS if tls else VHOST_TEMPLATE_HTTP
    content = template.format(name=upstream, domain=site.domain, port=port)

    if settings.dev_mode:
        log.info("[DEV] Would write vhost config to %s:\n%s", conf_path, content)
    else:
        conf_path.write_text(content)
        log.info("Wrote vhost config for %s -> %s", site.domain, conf_path)

    return conf_path


def remove_vhost(site_name: str) -> None:
    """Remove vhost config for a site."""
    conf_path = PROXY_CONF_DIR / f"{site_name}.conf"
    if settings.dev_mode:
        log.info("[DEV] Would remove vhost config %s", conf_path)
        return
    if conf_path.exists():
        conf_path.unlink()
        log.info("Removed vhost config %s", conf_path)


def reload_proxy() -> None:
    """Signal Nginx to reload its configuration."""
    if settings.dev_mode:
        log.info("[DEV] Would reload nginx")
        return

    import subprocess
    try:
        result = subprocess.run(
            ["docker", "exec", "proxy", "nginx", "-s", "reload"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode != 0:
            log.warning("nginx reload stderr: %s", result.stderr)
        else:
            log.info("Nginx reloaded")
    except Exception as exc:
        log.error("Failed to reload nginx: %s", exc)
